version: '3.0'

services:
  redis-token:
    image: redis:latest
    container_name: redis-token
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  rally-mate:
    image: phj0860/rally-mate:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: on-failure
    depends_on:
      - redis-token
    ports:
      - "9000:9000"

  rallymate-db:
    image: mysql:8.0.25
    restart: on-failure
    container_name: rallymate-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rallymate_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password    # secrets 파일 사용 시에는 prefix로 _FILE 필수
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql

secrets:
  mysql_root_password:
    file: /run/secrets/mysql_root_password.txt
  mysql_user:
    file: /run/secrets/mysql_user.txt
  mysql_password:
    file: /run/secrets/mysql_password.txt

volumes:
  mysql_data:
