CREATE TABLE `member` (
	`id`	INT UNSIGNED	NOT NULL PRIMARY KEY  AUTO_INCREMENT	COMMENT 'auto_increment',
	`name`	VARCHAR(50)	NOT NULL,
	`email`	VARCHAR(100)	NOT NULL,
	`password` TEXT NOT NULL,
	`status`    VARCHAR(30) NOT NULL DEFAULT 'ACTIVATE',
	`created_time` TIMESTAMP NOT NULL,
    `user_role` VARCHAR(30) NOT NULL
);


